sonar.projectKey=applaudo.SLM.slm-backend
sonar.sources=src
sonar.projectName=Applaudo: SLM - Node Backend
sonar.projectVersion=1.0
sonar.tests=src
sonar.test.inclusions=src/**/*.spec.ts,src/**/*.spec.jsx,src/**/*.test.ts,src/**/*.test.tsx
sonar.coverage.exclusions=src/index.tsx,src/registerServiceWorker.ts,src/reportWebVitals.ts,src/setupTests.ts,src/endpoints/*.ts,src/static/data/*.ts,src/hooks/useIsLogged.ts,src/components/VideoPlayer/Controls.ts,src/components/VideoPlayer/VideoPlayerUI.tsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
# sonar.testExecutionReportPaths=test-report.xml
sonar.eslint.reportPath=eslint.json